image: condaforge/mambaforge
stages:
  - test
  - build
  - deploy

Tests + Documentation:
  stage: test
  only:
    - main
    - development
    - merge_requests
  before_script:
    - export PIP_CACHE_DIR="/opt/cache/pip"
    - mamba env create -f environment.yml
    - source activate  
    - conda activate freegsnke
    - pip install git+https://${FREEGSFAST_CI_TOKEN}@github.com/farscape-project/freegsfast
    - pip install -e .
    - python -m pip install -r requirements-dev.txt
    - apt-get update
    - apt-get -y install build-essential
  script:
    # TESTS
    - python -m pytest -v
    # Formatting
    - black --check freegsnke/
    - isort --check --diff freegsnke/
    # EXAMPLES
    - jupyter nbconvert --execute --to notebook --inplace examples/machine_config.ipynb
    - jupyter nbconvert --execute --to notebook --inplace examples/basic_dynamical_evolution.ipynb
    - jupyter nbconvert --execute --to notebook --inplace examples/equilibrium_examples.ipynb
    - jupyter nbconvert --execute --to notebook --inplace examples/example_nonlinear_evolution_diverted.ipynb
    - jupyter nbconvert --execute --to notebook --inplace examples/example_nonlinear_evolution_limiter.ipynb
    # DOCUMENTATION
    - cd docs/
    - pip install -r requirements_docs.txt
    - bash build_documentation.sh
  artifacts:
    paths:
      - docs/_build/html
    expire_in: 1 hour

Deploy docs STFC cloud:
  image: kroniak/ssh-client
  dependencies:
    - "Tests + Documentation"
  stage: deploy
  before_script:
    - mkdir -p ~/.ssh
    - echo "$ID_RSA_FREEGSNKE" | base64 -d > ~/.ssh/id_rsa
    - chmod 700 ~/.ssh    
    - chmod 600 ~/.ssh/id_rsa    
    - eval "$(ssh-agent -s)"    
    - ssh-add ~/.ssh/id_rsa
  script:    
    - scp -o StrictHostKeyChecking=no -Cr docs/_build/html $STFC_CLOUD_USERNAME@172.16.110.116:./
  artifacts:
    expose_as: "docs_html"
    paths:
      - docs/_build/html/
    expire_in: never

  only:
    - main
    - development